apiVersion: v1
kind: Secret
metadata:
  name: payment-service-keda-secret
  labels:
    app: payment-service
type: Opaque
stringData:
  KEDA_RABBITMQ_HOST: amqp://payment_service:change-me@rabbitmq.example.internal:5672/
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payment-service-rabbitmq
  labels:
    app: payment-service
spec:
  scaleTargetRef:
    name: payment-service
  minReplicaCount: 2
  maxReplicaCount: 10
  cooldownPeriod: 60
  pollingInterval: 15
  triggers:
    - type: rabbitmq
      metadata:
        hostFromEnv: KEDA_RABBITMQ_HOST
        queueName: sellerlist.payment.order-created.v1
        mode: QueueLength
        value: "20"
